### ISSUE TITLE
Persistent Threads Error on ExitApp

### ISSUE THREAD

**Issue by ghost** [HotKeyIt/ahkdll-v2-release#12]
If you have an AHK script that creates a `#Persistent` Thread, then `Reload`, `ExitApp`, and other commands trigger a `CONTINUABLE EXCEPTION_ACCESS_VIOLATION` error.

```AutoHotkey
CritObj := CriticalObject({"counter": 0}) ; Create new critical object

AhkThread1 := AhkThread("
    (`
        #Persistent
        CritObj:=CriticalObject(A_Args[1])
    )", &CritObj ""
 )

Esc::ExitApp
```

1. Run Script
2. Press Escape to ExitApp
3. Get Error Message seen below

![](https://i.imgur.com/RURTdsq.png)

**Comment by ghost** [comment]
For reference, I tried terminating with `AhkThread1.ahkTerminate()` and `ahkthread_free(AhkThread1)` inside of an `OnExit` function, but that does not appear to work as I intended.

**Comment by andreguilhon** [comment]
I have this issue in my environment also, from time to time. Never figured it out what could be the problem. Will try to see if it has to do with your problem. 
Maybe will be easier to find out the problem.

**Comment by ghost** [comment]
Sounds good, took me quite a while to figure out what was going on and debug down to a specific test case.

**Comment by HotKeyIt** [comment]
This bug has been fixed now
