### ISSUE TITLE
I also cannot run ahk2exe

### ISSUE THREAD

**Issue by piterat** [HotKeyIt/ahkdll-v2-release#16]
I currently have vanilla autohotkey, and just downloaded autohotkey_h
trying to get ahk2exe.ahk file to work, it is stating I need to "Handle FileInstall on same-line If* commands"
I cant find anywhere in the documentation how to do this
   because I did not fix it, when i tried to run it, i did get a File Install error, but not sure how to fix it.
are you familiar with this? Please instruct how to fix

**Comment by HotKeyIt** [comment]
Please tell the steps you did, I am not sure how you could get that error.
Also you were surely looking for AHK_H v1: https://github.com/HotKeyIt/ahkdll-v1-release

**Comment by piterat** [comment]
the todo on the readme is

"TODO
----
Handle FileInstall on same-line If* commands."

I do not know how to do this. I have tried

1. replace compiler folder

2. copy and paste autohotkey.exe, or x64w .exe file or x64w_MT file
and rename to ahk2exe as instructed by several help articles

3. add folders from autohoutkey_H into autohotkey program files folder
try all 3 above

no matter what i try the fundamental error is the fileinstall line


please tell me how to fix this error or provide detailed steps on how
to go from vanilla (normal download of AHK) to properly install your
compiler

**Comment by HotKeyIt** [comment]
Download latest v1 or v2, extract and run Ahk2Exe.exe in compiler folder.
AHK_H v1: https://github.com/HotKeyIt/ahkdll-v1-release/archive/master.zip
AHK_H v2: https://github.com/HotKeyIt/ahkdll-v2-release/archive/master.zip
