### ISSUE TITLE
CreateScript Error Compiling with Custom Bin in Alternate Directory

### ISSUE THREAD

**Issue by ghost** [HotKeyIt/ahkdll-v2-release#18]
Attempting to compile using a CustomBin that is not in the `x64w` repo fails with a Syntax error.

Test Repo: https://github.com/Deafwave/ahkdll-v2-release/tree/testCompiler

Steps to Reproduce:

1. Execute `test\compileAll.exe` which will run `test\compileAll.ahk`
2. This will compile multiple files
3. Expected: All Pass
4. Actual: Syntax Error on CustomBin execution
  - [Error] Attempting to compile using CustomBin named `AutoHotkey.exe` with a custom 10-character password while placed in `ahkdll-v2-release\Compiler\AutoHotkey.exe`: https://i.imgur.com/2c9XOVcm.jpg

---

Working As Intended:
- Attempting to compile using x64w\AutoHotkey.exe with all variations, `AutoHotkey` default passsword: Working as Intended
- Attempting to compile using CustomBin named `AutoHotkey.exe` with a custom 10-character password while placed in `ahkdll-v2-release\x64w\AutoHotkey.exe`
  - Correct Password: **Working as Intended**
  - Incorrect Password: https://i.imgur.com/aBAEdNZ.png Working as Intended

**Comment by HotKeyIt** [comment]
This is because it uses the v1 lib, place the custom bin in Compiler\v2!
Ahk2Exe.ahk is necessary if Ahk2Exe.exe is not compiled!
Note, there is DirGetParent function that you can use.
Also best is to use quotes for command line, just to be sure:
```
RunWait("`"" Ahk2ExePath "`" `"" Ahk2ExeScript "`" /in `"" inScript "`" /out `"" outScript "`" /NoDecompile /pass oCKArYwIpx /bin `"" binToUse "`" /compress " compress)
```
