### ISSUE TITLE
CreateScript Include/IncludeAgain Not Working As Expected

### ISSUE THREAD

**Issue by ghost** [HotKeyIt/ahkdll-v2-release#19]
If you have an Include that two AHKThreads use at the same time, one of them does not receive the included content.

Test Repo: https://github.com/Deafwave/ahkdll-v2-release/tree/testCompilerIncludes

Steps to Reproduce:
1. [optional] Execute `test\compileAll.exe` which will run `test\compileAll.ahk`
2. [optional] This will compile two files to `test\compiled`
3. Run `test\compiled\testTwoIncludes.exe` to see Error https://i.imgur.com/N6w1MXb.png
4. Run `test\compiled\testTwoIncludeAgains` to see Error https://i.imgur.com/kTJjaqw.png

Expected: Two Message Boxes
Actual: One Message Box + Error or Error.

**Comment by HotKeyIt** [comment]
Obviously It will not work like that, one is not including the function (problem for thread) and the other includes it twice (problem for main exe).

I usually do one include for all functions (regardless if only one thread requires it or both) and another for each script:
```
#Persistent
#SingleInstance force
LO := AHKThread(CreateScript("ScriptOne:ScriptOneEnd`nFuncLib:FuncLibEnd", "oCKArYwIpx"))
LT := AHKThread(CreateScript("ScriptTwo:ScriptTwoEnd`nFuncLib:FuncLibEnd", "oCKArYwIpx"))
Sleep(2000)
Return

ScriptOne:
placeholder := "" ; Still using this to bypass the return error
#Include <testScriptOne>
ScriptOneEnd:
Return

ScriptTwo:
placeholder := "" ; Still using this to bypass the return error
#Include <testScriptTwo>
ScriptTwoEnd:
Return

FuncLib:
Return ; not relevant since below will contain functions and classes only.
#Include <funclib>
FuncLibEnd:
Return
```

**Comment by ghost** [comment]
Have had a delay in my development, but am looking at this now.

I see what you are doing, I'll have to reorganize my script to allow this and will see if it compiles.

EDIT: Running into many many errors, am trying to isolate the issue. This weird way of including files is still not working as I would expect. Will start working out of the Test Repo tomorrow to determine exactly where my issue is stemming from.
