### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by VaNnOrus** [HotKeyIt/ahkdll-v2-release#2]
Hi.

I copy all files from ahkdll v2 Compiler dir to installed AHK Compiler dir. Double click on Ahk2Exe.ahk and some error was happened in file ScriptParser.ahk on line 23: LoopRead, %ahk% (This line does not contain a recognized action)
![err](https://cloud.githubusercontent.com/assets/6804209/12093034/a4e1fc12-b311-11e5-80d7-df14424ae2c0.png)

Help me ;(

**Comment by HotKeyIt** [comment]
You have to copy AutoHotkey.exe from v2 release and rename it to Ahk2Exe.exe, then run it.
