### ISSUE TITLE
AhkThread() use v2's dll not work

### ISSUE THREAD

**Issue by telppa** [HotKeyIt/ahkdll-v2-release#20]
```
; OutputVar := AhkThread("msgbox 'abc'", "", 0, "AutoHotkeyU64_V1.dll") ; this work
OutputVar := AhkThread("msgbox 'abc'", "", 0, "AutoHotkeyU64_V2.dll")   ; this not work
```

; my exe is ahk_h_v1_x64.
; system win10 2016 ltsc.

**Comment by telppa** [comment]
After registering the dll of AutoHotkeyU64_V2, using the following code in ahk_h_v1_x64.exe still does not work.

```
AhkCom := ComObjCreate("AutoHotkey2.Script")
AhkCom.ahktextdll("MsgBox 'Hello World!`nExitApp'")
While AhkCom.ahkReady()
Sleep, 100
MsgBox Exiting now
```

**Comment by telppa** [comment]
After registering the dll of AutoHotkeyU64_V2, using the following code in ahk_h_v1_x64.exe still does not work.

```
hModule:=DllCall("LoadLibrary","Str",A_AhkDir "\AutoHotkeyU64_V2.dll")
ahk:=ComObjDll(hModule,"{FEEEC4BA-04AF-45F0-B385-7290C65CFB9B}") ; CLSID for Version 2.0
```
```
hModule:=DllCall("LoadLibrary","Str",A_AhkDir "\AutoHotkeyU64_V2.dll")
ahk:=ComObjDll(hModule,"{F1D0DE03-30FD-4326-B33F-989BBFAA5FFA}") ; CLSID for Version 2.0
```

**Comment by telppa** [comment]
Since  v2 is not compatible with v1, I would like to use v1_h.exe to call v2_h.dll to implement some new features without changing the old code.

I think this may be a better way to transition from v1 to v2.

**Comment by HotKeyIt** [comment]
V2 will not have COM dll, instead the exe will be COM enabled.
