### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by ci70** [HotKeyIt/ahkdll-v2-release#7]
Is this possible with AHK_V2_H?

> # BinaryCall UDF - Write Subroutines In C, Call In AutoIt
> https://www.autoitscript.com/forum/topic/162366-binarycall-udf-write-subroutines-in-c-call-in-autoit/
> # The Embedded Flat Assembler (FASM) UDF
> https://www.autoitscript.com/forum/topic/111613-the-embedded-flat-assembler-fasm-udf/
> # AutoIt Inline Assembly UDF
> https://www.autoitscript.com/forum/topic/86672-autoit-inline-assembly-udf/
> # Embed DLLs in script and call functions from memory (MemoryDll UDF)
> https://www.autoitscript.com/forum/topic/77463-embed-dlls-in-script-and-call-functions-from-memory-memorydll-udf/

**Comment by HotKeyIt** [comment]
BinaryCall: MCodeH - https://github.com/HotKeyIt/ahkdll/blob/master/source/resources/reslib/MCodeH.ahk
FASM and Inline Assembly should be possible to convert from autoit Code to ahk
MemoryLoadLibrary: http://hotkeyit.github.io/v2/docs/commands/MemoryLoadLibrary.htm

**Comment by ci70** [comment]
Would also be nice to have getopt/getopt_long/getopt_long_only.
For easy command line parse. What you think?

Maybe can use a GCC implementation?

**Comment by HotKeyIt** [comment]
Why, what is wrong with A_Args?

**Comment by ci70** [comment]
I think getopt is faster :))

**Comment by ci70** [comment]
Maybe statically link with C?

**Comment by HotKeyIt** [comment]
Not sure how you would do that and I don't think it will be faster.
Why do you need it to be faster?

**Comment by ci70** [comment]
Look how simple this is. A_Args is too complicated.
https://gist.github.com/drmalex07/6bcd65a0861f58b646a0

**Comment by ci70** [comment]
@HotKeyIt Is it possible to compiled getopt with GCC and then use MCODE?

**Comment by HotKeyIt** [comment]
Don't get what is complex with A_Args?
If getopt depends on other functions, it would be quite difficult to do trough MCODE but you could make a  dll.
