### ISSUE TITLE
AhkThread

### ISSUE THREAD

**Issue by ci70** [HotKeyIt/ahkdll-v2-release#8]
Can you simplify the threading? In OpenMP we can write this.

```
#include <stdio.h>
 
int main() {
  #pragma omp parallel
  {
    printf("https://helloacm.com\n");     
  }
  return 0;
}
```

**Comment by HotKeyIt** [comment]
See http://hotkeyit.github.io/v2/docs/commands/NewThread.htm
How is this not simple?
NewThread("MsgBox 'Message from Thread'")

**Comment by ci70** [comment]
Ah.
