### ISSUE TITLE
Implement missing functions

### ISSUE THREAD

**Issue by ci70** [HotKeyIt/ahkdll-v2-release#9]
Implement DllCallAddress, no such currently function right now in AHK.
https://www.autoitscript.com/autoit3/docs/functions/DllCallAddress.htm

As well as BinaryLen($key) and Binary($key) too.

**Comment by HotKeyIt** [comment]
https://autohotkey.com/boards/viewtopic.php?f=65&t=59670 ???

**Comment by ci70** [comment]
I am interested because of this.
https://www.autoitscript.com/forum/topic/162366-binarycall-udf-write-subroutines-in-c-call-in-autoit/

**Comment by HotKeyIt** [comment]
Search for MCode or use https://github.com/HotKeyIt/ahkdll/blob/master/source/resources/reslib/MCodeH.ahk

See also: http://hotkeyit.github.io/v2/docs/commands/MCodeH.htm
